add file citusdata-singlenode.yml
koding/stacks pull request #14
Opened 2017-01-24 06:20 UTC by hectork01

2017-01-24 06:34 UTC, szkl requested changes

2017-01-24 06:34 UTC, szkl commented on citusdata-singlenode.yml
> +        cat - <<EOF >> /var/lib/postgresql/init.sh
Input is missing.

2017-01-24 06:34 UTC, szkl commented on citusdata-singlenode.yml
> +        echo "export PATH=\$PATH:/usr/lib/postgresql/9.5/bin" >> /var/lib/postgresql/.profile
Is there any reference about this?

2017-01-24 06:34 UTC, szkl commented on citusdata-singlenode.yml
> +        sleep 3
It doesn't look like needed.

2017-01-24 06:34 UTC, szkl commented on citusdata-singlenode.yml
> +        echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf
These three commands can be folded into one like

```sh
echo "shared_preload_libraries = 'citus'" | tee --append citus/master/postgresql.conf citus/worker1/postgresql.conf citus/worker2/postgresql.conf
```

2017-01-24 06:34 UTC, szkl commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
```sh
for port in {9700..9702}; do psql -p $port -c "CREATE EXTENSION citus;"; done
```

2017-01-24 07:28 UTC, hectork01 commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
I'm having an error using that one: 
`
psql: invalid port number: "-c"
psql: invalid port number: "-c"
psql: invalid port number: "-c"
`

2017-01-24 09:01 UTC, szkl commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
I've updated the snippet.

2017-01-25 17:52 UTC, hectork01 commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
Still the same error.

2017-01-25 19:14 UTC, rjeczalik commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
The script is executed by /bin/sh, in order to make that working you'd need to add the bash shebang:

```
      user_data: |-
         #!/bin/bash
         set -e
         ...
```

2017-01-25 19:15 UTC, rjeczalik commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
And it should be:

```bash
for port in {9700..9702}; do ... 
```

Without the quoting.

2017-01-25 23:20 UTC, szkl commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
Right.

2017-01-26 04:45 UTC, hectork01 commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
@rjeczalik thanks, I already tried that, but still got the error:
```
server starting
server starting
server starting
psql: invalid port number: "-c"
psql: invalid port number: "-c"
psql: invalid port number: "-c"
```

How ever when running the command in the terminal it works just fine:
![image](https://cloud.githubusercontent.com/assets/20778330/22320112/4c6bf534-e357-11e6-89f9-bc45ddac9395.png)
@szkl maybe we should keep it as 3 lines of code instead as a loop.

2017-01-26 13:32 UTC, szkl requested changes

2017-01-26 13:32 UTC, szkl commented on citusdata-singlenode.yml
> +        psql -p 9700 -c "CREATE EXTENSION citus;"
Did you add `#!/bin/bash` to top?

2017-01-26 14:08 UTC, hectork01 commented
Not here, but when I test it, Yes I did add it.

2017-01-26 20:44 UTC, szkl requested changes

2017-01-26 20:44 UTC, szkl commented on citusdata-singlenode.yml
> +        set -e
```#!/bin/bash```

2017-01-26 21:25 UTC, hectork01 commented on citusdata-singlenode.yml
> +        set -e
![image](https://cloud.githubusercontent.com/assets/20778330/22350922/a5317784-e3e3-11e6-8c6f-5ff0b2bdac6f.png)
still the error:
![image](https://cloud.githubusercontent.com/assets/20778330/22350999/00cbc428-e3e4-11e6-824e-95831c8a8f44.png)

2017-01-26 21:53 UTC, szkl approved these changes

2017-01-26 21:53 UTC, merged