Update a few stacks
koding/stacks pull request #16
Opened 2017-04-05 17:59 UTC by htaslan

Modified stacks:
- `apache`
- `docker`
- `memsql`
- `nodejs`

2017-04-05 18:12 UTC, szkl commented on apache.yml
> +        cat <<-EOF >>$SHELLPROFILE
Can we benefit from /etc/issue file instead of a shell-specific profile script?

2017-04-05 18:13 UTC, szkl commented on apache.yml
> +        cat <<-EOF >>$SHELLPROFILE
s/issue/mot.d/

2017-04-05 18:29 UTC, szkl requested changes
Thanks, @htaslan. It looks okay overall. I have requested some syntactical changes.

2017-04-05 18:29 UTC, szkl commented on docker.yml
> +        apt-get install -y docker-ce --no-install-recommends
Put named options before positional arguments.

2017-04-05 18:29 UTC, szkl commented on apache.yml
> +        set -xe
Long option names, please.

2017-04-05 18:29 UTC, szkl commented on apache.yml
> +        apt-get install -y apache2 --no-install-recommends
Put named options before positional arguments and use long option name.

2017-04-05 18:29 UTC, szkl commented on docker.yml
> +        set -x
Long option names.

2017-04-05 18:29 UTC, szkl commented on docker.yml
> +        apt-get update && apt-get install -y \
And operator is redundant because `errexit` will cause an early exit if a failure occurs.

2017-04-05 18:29 UTC, szkl commented on docker.yml
> +          --no-install-recommends
Should be placed before positional arguments.

2017-04-05 18:29 UTC, szkl commented on docker.yml
> +        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
Long option names for readability's sake.

2017-04-05 18:29 UTC, szkl commented on memsql.yml
> +        set -x
Long option names.

2017-04-05 18:29 UTC, szkl commented on memsql.yml
> +        MEMSQL_VERSION="5.7.1"
I tend to use camel case for variables which are not exported to subprocesses.

2017-04-05 18:29 UTC, szkl commented on memsql.yml
> +        wget -qO- \
Long option names.

2017-04-05 18:29 UTC, szkl commented on memsql.yml
> +          "http://download.memsql.com/$MEMSQL_NAME/$MEMSQL_TARBALL" | tar -xvz
Long option names for `tar` too.

2017-04-05 18:29 UTC, szkl commented on nodejs.yml
> +        set -x
Long option names.

2017-04-05 18:29 UTC, szkl commented on nodejs.yml
> +        apt install -y wget --no-install-recommends
Named argument should be placed before positional arguments.

2017-04-05 18:29 UTC, szkl commented on nodejs.yml
> +        NODE_VERSION="v6.10.2"
Can you make it fetch latest LTS version automatically?

2017-04-05 18:29 UTC, szkl commented on nodejs.yml
> +        wget -qO- $NODE_DIST_URL | tar --extract --xz --strip-components=1 \
Long option names for `wget`.

2017-04-06 13:33 UTC, htaslan commented on apache.yml
> +        set -xe
i disagree with you. `set -euo pipefail` is a typical use.  therefore i think that there is no need to use the long option names. but, if Koding is using it in this way, there is no problem. I can fix it.

2017-04-06 13:42 UTC, szkl commented on apache.yml
> +        set -xe
I'm okay with it. I just don't make any exceptions for option names in shell scripts :)

2017-05-02 05:27 UTC, merged