New Stacks files
koding/stacks pull request #4
Opened 2016-10-17 21:08 UTC by hectork01

2016-10-19 20:29 UTC, szkl commented
Please drop all version suffixes from directory names.

2016-10-19 20:30 UTC, szkl commented
No need for self-explaining commands. E.g.

```bash
# Starting service
service foo start
```

2016-10-19 20:33 UTC, gokmen commented
what about creating a variable per stack template for versions instead of naming instances with the versions. we can use and parse that version if we need to, something like; `${var.service_version}`

2016-10-19 20:44 UTC, szkl commented
Remove all unused variables.

2016-10-19 21:08 UTC, szkl commented
Is it possible to use terraform variable for instance IP addresses?

2016-10-19 21:09 UTC, szkl commented
Please move any script in data directories located under /var/lib.

Replace inline generated start/stop scripts with proper init scripts. So, user can just start/stop services via `service`, `start`, `stop` commands.

2016-10-19 21:10 UTC, szkl commented
I'd extract tarballs into /usr/local instead of home directory.

2016-10-19 21:21 UTC, szkl commented
I think embedded (echo'd) files should be downloaded as a Gist for readability.

2016-10-21 06:15 UTC, szkl requested changes

2016-10-21 06:15 UTC, szkl commented on Citus-SingleNode.yml
> +        curl https://install.citusdata.com/community/deb.sh | sudo bash
No need for sudo.

2016-10-21 06:15 UTC, szkl commented on Citus-SingleNode.yml
> +        su postgres -c "sh /var/lib/postgresql/init.sh"
I think init.sh and citus/master/pg_worker_list.conf should be downloaded as a Gist on GitHub.

Init script and configuration files should reside in /etc/ directory instead of designated data directory.

Init script appends same lines to configuration files each time executed. It acts more like a prepare script rather than initializing postgresql service.

2016-10-21 06:15 UTC, szkl commented on Django.yml
> +        CODENAME=$(lsb_release -cs)
Remove unused variables.

2016-10-21 06:15 UTC, szkl commented on Druid-full.yml
> +        curl http://www.gtlib.gatech.edu/pub/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -o zookeeper-3.4.6.tar.gz
--output option with same file name is redundant.

2016-10-21 06:15 UTC, szkl commented on Druid-full.yml
> +        tar -xzf zookeeper-3.4.6.tar.gz -C /home/$KODING_USER/
You can pipe curl output into tar.

Long option names are much readable in a script file.

2016-10-21 06:15 UTC, szkl commented on Druid-full.yml
> +        tar -xzf druid-0.9.1.1-bin.tar.gz -C /home/$KODING_USER/
Likewise.

2016-10-21 06:15 UTC, szkl commented on Druid-full.yml
> +        su $KODING_USER -c "sh /home/$KODING_USER/exec.sh"
You can define a function like

``` bash
pushd $HOME/zookeeper-3.4.6
function start-service() {
  bin/$1.sh start
  sleep 3
}
```

A gist would be much more readable for an embedded script.

2016-10-21 06:15 UTC, szkl commented on WorldPress.yml
> +# Here is your stack preview
It is WordPress.

2016-10-21 06:15 UTC, szkl commented on Docker.yml
> +# Here is your stack preview
This is already submitted in https://github.com/koding/stacks/pull/1.

2016-10-21 06:15 UTC, szkl commented on Postgres-Replication.yml
> +  aws_instance:
These instances need static IP addresses.

2016-10-21 06:15 UTC, szkl commented on Redis.yml
> +        curl -O http://download.redis.io/releases/redis-3.2.3.tar.gz
How about [this](https://launchpad.net/~chris-lea/+archive/ubuntu/redis-server) PPA?

2016-10-21 06:18 UTC, szkl requested changes

2016-10-21 06:18 UTC, szkl commented on Docker.yml
> +# Here is your stack preview
Please remove this file from this pull request.

2016-10-21 06:25 UTC, szkl commented
Please pull changes in master.

2016-10-21 15:51 UTC, hectork01 commented on Citus-SingleNode.yml
> +        su postgres -c "sh /var/lib/postgresql/init.sh"
Actually, it is a initial configuration script, not a service script. then only runs the one first time.

2016-10-24 19:17 UTC, hectork01 commented on Django.yml
> +        CODENAME=$(lsb_release -cs)
Done

2016-10-24 19:18 UTC, hectork01 commented on Docker.yml
> +# Here is your stack preview
Done

2016-10-24 21:51 UTC, rjeczalik commented on Druid-full.yml
> +        curl http://www.gtlib.gatech.edu/pub/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz -o zookeeper-3.4.6.tar.gz
It's curl not wget.

2016-11-11 06:11 UTC, szkl commented
Any updates?

2016-11-11 17:06 UTC, hectork01 commented
I did change most of your suggestions, did you checked them?

2016-12-05 19:57 UTC, hectork01 commented on Citus-SingleNode.yml
> +        curl https://install.citusdata.com/community/deb.sh | sudo bash
Done

2016-12-27 22:13 UTC, hectork01 commented on Postgres-Replication.yml
> +  aws_instance:
done

2016-12-27 22:16 UTC, hectork01 commented on WorldPress.yml
> +# Here is your stack preview
done

2016-12-28 01:23 UTC, hectork01 commented on Redis.yml
> +        curl -O http://download.redis.io/releases/redis-3.2.3.tar.gz
That will be easier but this PPA installs version 3.0.7, now the latest stable version is 3.2.6,  change it to be able to install different versions by using the variable $VERSION

2017-01-05 06:52 UTC, sinan commented
@szkl ping.

2017-01-10 17:09 UTC, szkl requested changes
Latest changes are okay. You need to fix new lines, though. You can see `^M` chars in diff page.

2017-01-17 22:35 UTC, hectork01 commented
Actually I test the code in koding and then copy/paste it here, and those chars only shows here, I tried editing the files online here in the Github page and is the same thing, it's weird because i've been doing the same procedure as before, I also tried to delete the lines but it is not fixing it either. Maybe it is because I'm using windows, I'll try to fix it in Linux.

2017-01-17 23:08 UTC, rjeczalik commented
@hectork01 It may depend on your git client configuration - during installation `as-is` should be chosen when asked about line endings. Just guessing.

2017-01-18 02:05 UTC, closed without merging